# Deployment configuration for the Sales App

deployment:
  tasks:
    - export DEPLOY_ENVIRONMENT=production
    - export FLASK_APP=app.py
    - export DATABASE_URL="mysql+pymysql://impapnvs_impact:ImpactLife1212@localhost/impapnvs_sales_app"
    - echo "Deployment started: Setting up environment variables"

    # Copy backend to the subdomain folder "salesback.impactlife.com.gh"
    - run:
        command: |
          echo "Copying backend files to salesback.impactlife.com.gh"
          mkdir -p ~/salesback.impactlife.com.gh
          rsync -av --exclude frontend --exclude public_html --exclude .git . ~/salesback.impactlife.com.gh/

    # Install Python dependencies in the backend folder
    - run:
        command: |
          echo "Installing backend dependencies"
          cd ~/salesback.impactlife.com.gh
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

    # Set up the frontend build process
    - run:
        command: |
          echo "Building the frontend"
          cd frontend
          npm install
          npm run build
          cd ..

    # Copy the frontend to the subdomain folder "salesapp.impactlife.com.gh"
    - run:
        command: |
          echo "Copying frontend build to salesapp.impactlife.com.gh"
          mkdir -p ~/salesapp.impactlife.com.gh
          rsync -av frontend/build/ ~/salesapp.impactlife.com.gh/

    # Apply database migrations (Alembic) in the backend folder
    - run:
        command: |
          echo "Applying database migrations"
          cd ~/salesback.impactlife.com.gh
          source venv/bin/activate
          alembic upgrade head

    # Finalize deployment
    - run:
        command: |
          echo "Deployment finished successfully"

    # Restart the web server to apply changes
    - restart_web_server
