"""2nds

Revision ID: b99ac5e037fe
Revises: ec554686807f
Create Date: 2024-09-02 10:48:38.065717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99ac5e037fe'
down_revision = 'ec554686807f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_code', sa.String(length=255), nullable=True))
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('sort_code')

    # ### end Alembic commands ###
