"""Initial migration

Revision ID: ff352a13d75d
Revises: 
Create Date: 2024-09-04 23:20:18.153322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff352a13d75d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_name'), ['name'], unique=True)

    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('ghpost_gps', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_name'), ['name'], unique=True)

    op.create_table('impact_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_product_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_product_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_product_name'), ['name'], unique=False)

    op.create_table('paypoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paypoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paypoint_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_paypoint_name'), ['name'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bank_branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('sort_code', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_branch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_branch_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_branch_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_branch_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('microsoft_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_microsoft_id'), ['microsoft_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role_id'), ['role_id'], unique=False)

    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_trail_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_user_id'), ['user_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_user_id'), ['user_id'], unique=False)

    op.create_table('sales_executive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_executive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_executive_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_executive_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_executive_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_executive_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_executive_phone_number'), ['phone_number'], unique=False)

    op.create_table('user_branches',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'branch_id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sale_manager', sa.String(length=100), nullable=False),
    sa.Column('sales_executive_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('client_phone', sa.String(length=10), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('momo_reference_number', sa.String(length=100), nullable=True),
    sa.Column('momo_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('first_pay_with_momo', sa.Boolean(), nullable=True),
    sa.Column('subsequent_pay_source_type', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('bank_acc_number', sa.String(length=100), nullable=True),
    sa.Column('paypoint_name', sa.String(length=100), nullable=True),
    sa.Column('paypoint_branch', sa.String(length=100), nullable=True),
    sa.Column('staff_id', sa.String(length=100), nullable=True),
    sa.Column('policy_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('geolocation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('customer_called', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['policy_type_id'], ['impact_product.id'], ),
    sa.ForeignKeyConstraint(['sales_executive_id'], ['sales_executive.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_bank_acc_number'), ['bank_acc_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_bank_branch'), ['bank_branch'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_bank_name'), ['bank_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_client_phone'), ['client_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_first_pay_with_momo'), ['first_pay_with_momo'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_momo_reference_number'), ['momo_reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_momo_transaction_id'), ['momo_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_paypoint_branch'), ['paypoint_branch'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_paypoint_name'), ['paypoint_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_policy_type_id'), ['policy_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_sale_manager'), ['sale_manager'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_sales_executive_id'), ['sales_executive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_subsequent_pay_source_type'), ['subsequent_pay_source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_user_id'), ['user_id'], unique=False)

    op.create_table('sales_executive_branches',
    sa.Column('sales_executive_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['sales_executive_id'], ['sales_executive.id'], ),
    sa.PrimaryKeyConstraint('sales_executive_id', 'branch_id')
    )
    op.create_table('under_investigation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notes_history', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('under_investigation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_under_investigation_sale_id'), ['sale_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('under_investigation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_under_investigation_sale_id'))

    op.drop_table('under_investigation')
    op.drop_table('sales_executive_branches')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_user_id'))
        batch_op.drop_index(batch_op.f('ix_sale_subsequent_pay_source_type'))
        batch_op.drop_index(batch_op.f('ix_sale_status'))
        batch_op.drop_index(batch_op.f('ix_sale_staff_id'))
        batch_op.drop_index(batch_op.f('ix_sale_source_type'))
        batch_op.drop_index(batch_op.f('ix_sale_serial_number'))
        batch_op.drop_index(batch_op.f('ix_sale_sales_executive_id'))
        batch_op.drop_index(batch_op.f('ix_sale_sale_manager'))
        batch_op.drop_index(batch_op.f('ix_sale_policy_type_id'))
        batch_op.drop_index(batch_op.f('ix_sale_paypoint_name'))
        batch_op.drop_index(batch_op.f('ix_sale_paypoint_branch'))
        batch_op.drop_index(batch_op.f('ix_sale_momo_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_sale_momo_reference_number'))
        batch_op.drop_index(batch_op.f('ix_sale_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sale_first_pay_with_momo'))
        batch_op.drop_index(batch_op.f('ix_sale_client_phone'))
        batch_op.drop_index(batch_op.f('ix_sale_client_name'))
        batch_op.drop_index(batch_op.f('ix_sale_bank_name'))
        batch_op.drop_index(batch_op.f('ix_sale_bank_branch'))
        batch_op.drop_index(batch_op.f('ix_sale_bank_acc_number'))

    op.drop_table('sale')
    op.drop_table('user_branches')
    with op.batch_alter_table('sales_executive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_executive_phone_number'))
        batch_op.drop_index(batch_op.f('ix_sales_executive_name'))
        batch_op.drop_index(batch_op.f('ix_sales_executive_manager_id'))
        batch_op.drop_index(batch_op.f('ix_sales_executive_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sales_executive_code'))

    op.drop_table('sales_executive')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_is_deleted'))

    op.drop_table('report')
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trail_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_timestamp'))

    op.drop_table('audit_trail')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_microsoft_id'))
        batch_op.drop_index(batch_op.f('ix_user_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('bank_branch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_branch_name'))
        batch_op.drop_index(batch_op.f('ix_bank_branch_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bank_branch_bank_id'))

    op.drop_table('bank_branch')
    op.drop_table('role')
    with op.batch_alter_table('paypoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paypoint_name'))
        batch_op.drop_index(batch_op.f('ix_paypoint_is_deleted'))

    op.drop_table('paypoint')
    with op.batch_alter_table('impact_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_product_name'))
        batch_op.drop_index(batch_op.f('ix_impact_product_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_impact_product_category'))

    op.drop_table('impact_product')
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_name'))
        batch_op.drop_index(batch_op.f('ix_branch_is_deleted'))

    op.drop_table('branch')
    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_name'))
        batch_op.drop_index(batch_op.f('ix_bank_is_deleted'))

    op.drop_table('bank')
    # ### end Alembic commands ###
